In [5]:
import boto3
import pandas as pd

s3 = boto3.client("s3")

obj = s3.get_object(Bucket="nyc-taxi-ml-sangeeth", Key="processed/yellow_tripdata_2016_clean.csv")

# No .read() â†’ stream directly
chunks = pd.read_csv(obj["Body"], chunksize=100000)

for i, chunk in enumerate(chunks):
    print(f"Chunk {i} shape:", chunk.shape)
    # process chunk here instead of concatenating everything

Chunk 0 shape: (100000, 20)
Chunk 1 shape: (100000, 20)
Chunk 2 shape: (100000, 20)
Chunk 3 shape: (100000, 20)
Chunk 4 shape: (100000, 20)
Chunk 5 shape: (100000, 20)
Chunk 6 shape: (100000, 20)
Chunk 7 shape: (100000, 20)
Chunk 8 shape: (100000, 20)
Chunk 9 shape: (100000, 20)
Chunk 10 shape: (100000, 20)
Chunk 11 shape: (100000, 20)
Chunk 12 shape: (100000, 20)
Chunk 13 shape: (100000, 20)
Chunk 14 shape: (100000, 20)
Chunk 15 shape: (100000, 20)
Chunk 16 shape: (100000, 20)
Chunk 17 shape: (100000, 20)
Chunk 18 shape: (100000, 20)
Chunk 19 shape: (100000, 20)
Chunk 20 shape: (100000, 20)
Chunk 21 shape: (100000, 20)
Chunk 22 shape: (100000, 20)
Chunk 23 shape: (100000, 20)
Chunk 24 shape: (100000, 20)
Chunk 25 shape: (100000, 20)
Chunk 26 shape: (100000, 20)
Chunk 27 shape: (100000, 20)
Chunk 28 shape: (100000, 20)
Chunk 29 shape: (100000, 20)
Chunk 30 shape: (100000, 20)
Chunk 31 shape: (100000, 20)
Chunk 32 shape: (100000, 20)
Chunk 33 shape: (100000, 20)
Chunk 34 shape: (100000, 20)
Chunk 35 shape: (100000, 20)
Chunk 36 shape: (100000, 20)
Chunk 37 shape: (100000, 20)
Chunk 38 shape: (100000, 20)
Chunk 39 shape: (100000, 20)
Chunk 40 shape: (100000, 20)
Chunk 41 shape: (100000, 20)
Chunk 42 shape: (100000, 20)
Chunk 43 shape: (100000, 20)
Chunk 44 shape: (100000, 20)
Chunk 45 shape: (100000, 20)
Chunk 46 shape: (100000, 20)
Chunk 47 shape: (100000, 20)
Chunk 48 shape: (100000, 20)
Chunk 49 shape: (100000, 20)
Chunk 50 shape: (100000, 20)
Chunk 51 shape: (100000, 20)
Chunk 52 shape: (100000, 20)
Chunk 53 shape: (100000, 20)
Chunk 54 shape: (100000, 20)
Chunk 55 shape: (100000, 20)
Chunk 56 shape: (100000, 20)
Chunk 57 shape: (100000, 20)
Chunk 58 shape: (100000, 20)
Chunk 59 shape: (100000, 20)
Chunk 60 shape: (100000, 20)
Chunk 61 shape: (100000, 20)
Chunk 62 shape: (100000, 20)
Chunk 63 shape: (100000, 20)
Chunk 64 shape: (100000, 20)
Chunk 65 shape: (100000, 20)
Chunk 66 shape: (100000, 20)
Chunk 67 shape: (100000, 20)
Chunk 68 shape: (100000, 20)
Chunk 69 shape: (100000, 20)
Chunk 70 shape: (100000, 20)
Chunk 71 shape: (100000, 20)
Chunk 72 shape: (100000, 20)
Chunk 73 shape: (100000, 20)
Chunk 74 shape: (100000, 20)
Chunk 75 shape: (100000, 20)
Chunk 76 shape: (100000, 20)
Chunk 77 shape: (100000, 20)
Chunk 78 shape: (100000, 20)
Chunk 79 shape: (100000, 20)
Chunk 80 shape: (100000, 20)
Chunk 81 shape: (100000, 20)
Chunk 82 shape: (100000, 20)
Chunk 83 shape: (100000, 20)
Chunk 84 shape: (100000, 20)
Chunk 85 shape: (100000, 20)
Chunk 86 shape: (100000, 20)
Chunk 87 shape: (100000, 20)
Chunk 88 shape: (100000, 20)
Chunk 89 shape: (100000, 20)
Chunk 90 shape: (100000, 20)
Chunk 91 shape: (100000, 20)
Chunk 92 shape: (100000, 20)
Chunk 93 shape: (100000, 20)
Chunk 94 shape: (100000, 20)
Chunk 95 shape: (100000, 20)
Chunk 96 shape: (100000, 20)
Chunk 97 shape: (100000, 20)
Chunk 98 shape: (100000, 20)
Chunk 99 shape: (100000, 20)
Chunk 100 shape: (100000, 20)
Chunk 101 shape: (100000, 20)
Chunk 102 shape: (100000, 20)
Chunk 103 shape: (100000, 20)
Chunk 104 shape: (100000, 20)
Chunk 105 shape: (100000, 20)
Chunk 106 shape: (100000, 20)
Chunk 107 shape: (100000, 20)
Chunk 108 shape: (100000, 20)
Chunk 109 shape: (3051, 20)

In [6]:
for chunk in chunks:
    # e.g. keep only certain columns
    chunk = chunk[["passenger_count", "trip_distance"]]
    print(chunk.head())

In [7]:
chunk.head()

,store_and_fwd_flag,extra,improvement_surcharge,pickup_month,pickup_day_of_week,pickup_is_weekend,dropoff_month,dropoff_day_of_week,dropoff_is_weekend,delta_lat,delta_lon,is_single_passenger,trip_distance,fare_amount,mta_tax,tip_amount,tolls_amount,total_amount,haversine_km,extra_log
10900000,0,0.0,0.3,1,4,0,1,4,0,-0.016602,-0.020401,1,1.061257,2.484907,0.405465,1.098612,0.0,2.694627,1.259018,0.0
10900001,0,0.0,0.3,1,4,0,1,4,0,-0.020290,-0.014374,0,0.982078,2.351375,0.405465,1.408545,0.0,2.666534,1.269900,0.0
10900002,0,0.0,0.3,1,4,0,1,4,0,0.010994,0.009247,1,0.788457,2.079442,0.405465,0.000000,0.0,2.174752,0.895814,0.0
10900003,0,0.0,0.3,1,4,0,1,4,0,0.034294,0.026939,1,1.371181,2.772589,0.405465,1.425515,0.0,2.993730,1.693281,0.0
10900004,0,0.0,0.3,1,4,0,1,4,0,-0.007641,-0.013985,0,0.788457,2.251292,0.405465,0.693147,0.0,2.424803,0.897003,0.0